+ PYTHONPATH=/usr/src/RPM/BUILD/cinderclient-9.6.0
+ sphinx-build-3 doc/source html
Running Sphinx v8.2.1
loading translations [en]... done
[openstackdocstheme] version: 3.5.0
[openstackdocstheme] connecting html-page-context event handler
making output directory... done
[openstackdocstheme] overriding configured project name (Project name not set) with name extracted from the package (python-cinderclient); you can disable this behavior with the 'openstackdocs_auto_name' option
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
[openstackdocstheme] using theme from /usr/lib/python3/site-packages/openstackdocstheme/theme
fatal: not a git repository (or any of the parent directories): .git
[openstackdocstheme] cannot find git top directory, assuming "."
[openstackdocstheme] no ./.gitreview found
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 8 source files that are out of date
updating environment: [new config] 8 added, 0 changed, 0 removed
reading sources... [ 12%] cli/details
Generating CLI docs API Version Major: 3, Minor: 71
reading sources... [ 25%] cli/index
reading sources... [ 38%] contributor/contributing
copying assets... 
copying static files... 
copying static files... 
Writing evaluated template result to /usr/src/RPM/BUILD/cinderclient-9.6.0/html/_static/language_data.js
Writing evaluated template result to /usr/src/RPM/BUILD/cinderclient-9.6.0/html/_static/language_data.js
Writing evaluated template result to /usr/src/RPM/BUILD/cinderclient-9.6.0/html/_static/documentation_options.js
Writing evaluated template result to /usr/src/RPM/BUILD/cinderclient-9.6.0/html/_static/documentation_options.js
Writing evaluated template result to /usr/src/RPM/BUILD/cinderclient-9.6.0/html/_static/basic.css
Writing evaluated template result to /usr/src/RPM/BUILD/cinderclient-9.6.0/html/_static/basic.css
copying static files: done
copying static files: done
copying static files: done
copying extra files... 
copying extra files... 
copying extra files... 
copying extra files: done
copying extra files: done
copying extra files: done
copying assets: done
copying assets: done
copying assets: done
writing output... [ 12%] cli/details
writing output... [ 12%] cli/details
writing output... [ 12%] cli/details
writing output... [ 12%] cli/details
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[openstackdocstheme] Could not get modification time of doc/source/cli/details.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/cli/details.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/cli/details.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/cli/details.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/cli/details.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/cli/details.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/cli/details.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/cli/details.rst']' returned non-zero exit status 128.
[openstackdocstheme] could not determine last_updated for 'cli/details'
[openstackdocstheme] could not determine last_updated for 'cli/details'
[openstackdocstheme] could not determine last_updated for 'cli/details'
[openstackdocstheme] could not determine last_updated for 'cli/details'
[openstackdocstheme] could not determine last_updated for 'cli/details'
writing output... [ 25%] cli/index
writing output... [ 25%] cli/index
writing output... [ 25%] cli/index
writing output... [ 25%] cli/index
writing output... [ 25%] cli/index
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[openstackdocstheme] Could not get modification time of doc/source/cli/index.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/cli/index.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/cli/index.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/cli/index.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/cli/index.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/cli/index.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/cli/index.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/cli/index.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/cli/index.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/cli/index.rst']' returned non-zero exit status 128.
[openstackdocstheme] could not determine last_updated for 'cli/index'
[openstackdocstheme] could not determine last_updated for 'cli/index'
[openstackdocstheme] could not determine last_updated for 'cli/index'
[openstackdocstheme] could not determine last_updated for 'cli/index'
[openstackdocstheme] could not determine last_updated for 'cli/index'
[openstackdocstheme] could not determine last_updated for 'cli/index'
writing output... [ 38%] contributor/contributing
writing output... [ 38%] contributor/contributing
writing output... [ 38%] contributor/contributing
writing output... [ 38%] contributor/contributing
writing output... [ 38%] contributor/contributing
writing output... [ 38%] contributor/contributing
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[openstackdocstheme] Could not get modification time of doc/source/contributor/contributing.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/contributing.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/contributing.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/contributing.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/contributing.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/contributing.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/contributing.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/contributing.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/contributing.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/contributing.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/contributing.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/contributing.rst']' returned non-zero exit status 128.
[openstackdocstheme] could not determine last_updated for 'contributor/contributing'
[openstackdocstheme] could not determine last_updated for 'contributor/contributing'
[openstackdocstheme] could not determine last_updated for 'contributor/contributing'
[openstackdocstheme] could not determine last_updated for 'contributor/contributing'
[openstackdocstheme] could not determine last_updated for 'contributor/contributing'
[openstackdocstheme] could not determine last_updated for 'contributor/contributing'
writing output... [ 50%] contributor/functional_tests
writing output... [ 50%] contributor/functional_tests
writing output... [ 50%] contributor/functional_tests
writing output... [ 50%] contributor/functional_tests
writing output... [ 50%] contributor/functional_tests
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[openstackdocstheme] Could not get modification time of doc/source/contributor/functional_tests.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/functional_tests.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/functional_tests.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/functional_tests.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/functional_tests.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/functional_tests.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/functional_tests.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/functional_tests.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/functional_tests.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/functional_tests.rst']' returned non-zero exit status 128.
[openstackdocstheme] could not determine last_updated for 'contributor/functional_tests'
[openstackdocstheme] could not determine last_updated for 'contributor/functional_tests'
[openstackdocstheme] could not determine last_updated for 'contributor/functional_tests'
[openstackdocstheme] could not determine last_updated for 'contributor/functional_tests'
[openstackdocstheme] could not determine last_updated for 'contributor/functional_tests'
[openstackdocstheme] could not determine last_updated for 'contributor/functional_tests'
writing output... [ 62%] contributor/unit_tests
writing output... [ 62%] contributor/unit_tests
writing output... [ 62%] contributor/unit_tests
writing output... [ 62%] contributor/unit_tests
writing output... [ 62%] contributor/unit_tests
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[openstackdocstheme] Could not get modification time of doc/source/contributor/unit_tests.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/unit_tests.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/unit_tests.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/unit_tests.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/unit_tests.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/unit_tests.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/unit_tests.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/unit_tests.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/contributor/unit_tests.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/contributor/unit_tests.rst']' returned non-zero exit status 128.
[openstackdocstheme] could not determine last_updated for 'contributor/unit_tests'
[openstackdocstheme] could not determine last_updated for 'contributor/unit_tests'
[openstackdocstheme] could not determine last_updated for 'contributor/unit_tests'
[openstackdocstheme] could not determine last_updated for 'contributor/unit_tests'
[openstackdocstheme] could not determine last_updated for 'contributor/unit_tests'
[openstackdocstheme] could not determine last_updated for 'contributor/unit_tests'
writing output... [ 75%] index
writing output... [ 75%] index
writing output... [ 75%] index
writing output... [ 75%] index
writing output... [ 75%] index
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[openstackdocstheme] Could not get modification time of doc/source/index.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/index.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/index.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/index.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/index.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/index.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/index.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/index.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/index.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/index.rst']' returned non-zero exit status 128.
[openstackdocstheme] could not determine last_updated for 'index'
[openstackdocstheme] could not determine last_updated for 'index'
[openstackdocstheme] could not determine last_updated for 'index'
[openstackdocstheme] could not determine last_updated for 'index'
[openstackdocstheme] could not determine last_updated for 'index'
writing output... [ 88%] user/no_auth
writing output... [ 88%] user/no_auth
writing output... [ 88%] user/no_auth
writing output... [ 88%] user/no_auth
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[openstackdocstheme] Could not get modification time of doc/source/user/no_auth.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/user/no_auth.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/user/no_auth.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/user/no_auth.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/user/no_auth.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/user/no_auth.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/user/no_auth.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/user/no_auth.rst']' returned non-zero exit status 128.
[openstackdocstheme] could not determine last_updated for 'user/no_auth'
[openstackdocstheme] could not determine last_updated for 'user/no_auth'
[openstackdocstheme] could not determine last_updated for 'user/no_auth'
[openstackdocstheme] could not determine last_updated for 'user/no_auth'
writing output... [100%] user/shell
writing output... [100%] user/shell
writing output... [100%] user/shell
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
[openstackdocstheme] Could not get modification time of doc/source/user/shell.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/user/shell.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/user/shell.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/user/shell.rst']' returned non-zero exit status 128.
[openstackdocstheme] Could not get modification time of doc/source/user/shell.rst: Command '['git', 'log', '-n1', '--format=%ad', '--date=format:%Y-%m-%d %H:%M:%S', '--', 'doc/source/user/shell.rst']' returned non-zero exit status 128.
[openstackdocstheme] could not determine last_updated for 'user/shell'
[openstackdocstheme] could not determine last_updated for 'user/shell'
[openstackdocstheme] could not determine last_updated for 'user/shell'


WARNING: [openstackdocstheme] cannot get gitsha from git repository
WARNING: [openstackdocstheme] cannot get gitsha from git repository
generating indices... genindex done
generating indices... genindex done
writing additional pages... search done
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 1 warning.

The HTML pages are in html.
+ sphinx-build-3 -b man doc/source man
Running Sphinx v8.2.1
loading translations [en]... done
[openstackdocstheme] version: 3.5.0
[openstackdocstheme] connecting html-page-context event handler
making output directory... done
[openstackdocstheme] overriding configured project name (Project name not set) with name extracted from the package (python-cinderclient); you can disable this behavior with the 'openstackdocs_auto_name' option
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
[openstackdocstheme] using theme from /usr/lib/python3/site-packages/openstackdocstheme/theme
fatal: not a git repository (or any of the parent directories): .git
[openstackdocstheme] cannot find git top directory, assuming "."
[openstackdocstheme] no ./.gitreview found
building [mo]: targets for 0 po files that are out of date
writing output... 
building [man]: all manpages
updating environment: [new config] 8 added, 0 changed, 0 removed
reading sources... [ 12%] cli/details
Generating CLI docs API Version Major: 3, Minor: 71
reading sources... [ 25%] cli/index
reading sources... [ 38%] contributor/contributing
{1} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_get_string [0.001034s] ... ok
{1} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_invalid_version_strings_12_2_1_ [0.000514s] ... ok
{1} cinderclient.tests.unit.test_api_versions.DiscoverVersionTestCase.test_get_highest_version [0.001151s] ... ok
{1} cinderclient.tests.unit.test_api_versions.DiscoverVersionTestCase.test_get_highest_version [0.001151s] ... ok
{1} cinderclient.tests.unit.test_base.BaseTest.test__list_no_link [0.000645s] ... ok
{1} cinderclient.tests.unit.test_base.BaseTest.test__list_no_link [0.000645s] ... ok
{1} cinderclient.tests.unit.test_base.BaseTest.test_getid [0.000444s] ... ok
{1} cinderclient.tests.unit.test_base.BaseTest.test_getid [0.000444s] ... ok
{1} cinderclient.tests.unit.test_base.BaseTest.test_getid [0.000444s] ... ok
{1} cinderclient.tests.unit.test_base.DictWithMetaTest.test_dict_with_meta [0.000993s] ... ok
{1} cinderclient.tests.unit.test_base.DictWithMetaTest.test_dict_with_meta [0.000993s] ... ok
{1} cinderclient.tests.unit.test_base.DictWithMetaTest.test_dict_with_meta [0.000993s] ... ok
{1} cinderclient.tests.unit.test_client.ClientTest.test_construct_http_client_endpoint_url [0.000796s] ... ok
{1} cinderclient.tests.unit.test_client.ClientTest.test_construct_http_client_endpoint_url [0.000796s] ... ok
{1} cinderclient.tests.unit.test_client.ClientTest.test_construct_http_client_endpoint_url [0.000796s] ... ok
{1} cinderclient.tests.unit.test_client.ClientTest.test_get_client_class_unknown [0.000476s] ... ok
{1} cinderclient.tests.unit.test_client.ClientTest.test_get_client_class_unknown [0.000476s] ... ok
{1} cinderclient.tests.unit.test_client.ClientTest.test_get_client_class_unknown [0.000476s] ... ok
/usr/lib/python3/site-packages/keystoneauth1/adapter.py:278: UserWarning: Using keystoneclient sessions has been deprecated. Please update your software to use keystoneauth1.
/usr/lib/python3/site-packages/keystoneauth1/adapter.py:278: UserWarning: Using keystoneclient sessions has been deprecated. Please update your software to use keystoneauth1.
/usr/lib/python3/site-packages/keystoneauth1/adapter.py:278: UserWarning: Using keystoneclient sessions has been deprecated. Please update your software to use keystoneauth1.
  warnings.warn(
  warnings.warn(
  warnings.warn(
{1} cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method_raises_badrequest [0.018512s] ... FAILED
{1} cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method_raises_badrequest [0.018512s] ... FAILED
{1} cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method_raises_badrequest [0.018512s] ... FAILED



Captured traceback:
Captured traceback:
Captured traceback:
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
    Traceback (most recent call last):
    Traceback (most recent call last):



      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 192, in test_sessionclient_request_method_raises_badrequest
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 192, in test_sessionclient_request_method_raises_badrequest
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 192, in test_sessionclient_request_method_raises_badrequest
    self.assertRaises(exceptions.BadRequest, session_client.request,
    self.assertRaises(exceptions.BadRequest, session_client.request,


      File "/usr/lib/python3/site-packages/testtools/testcase.py", line 495, in assertRaises
    self.assertThat(our_callable, matcher)
    if raise_exc and resp.status_code >= 400:
                     ^^^^^^^^^^^^^^^^^^^^^^^

    TypeError: '>=' not supported between instances of 'Mock' and 'int'

{1} cinderclient.tests.unit.test_client.GetAPIVersionTestCase.test_get_server_version_1_http___192_168_122_127_8776_v3_e5526285ebd741b1819393f772f11fc3 [0.000963s] ... ok
{1} cinderclient.tests.unit.test_client.GetAPIVersionTestCase.test_get_server_version_3_http___192_168_122_127_volumesv3_e5526285ebd741b1819393f772f11fc3 [0.000881s] ... ok
{1} cinderclient.tests.unit.test_http.ClientTest.test_get [0.003175s] ... ok
usage: run.py [--test-parameter] [--test_parameter]
{1} cinderclient.tests.unit.test_http.ClientTest.test_get_retry_timeout_error [0.000835s] ... ok
error: ambiguous option: --test could match --test-parameter, --test_parameter
Try 'run.py help ' for more information.
{1} cinderclient.tests.unit.test_shell.CinderClientArgumentParserTest.test_raise_ambiguity_error_two_visible_argument [0.004751s] ... ok
{1} cinderclient.tests.unit.test_shell.ShellTest.test_auth_type_env [0.005185s] ... ok
{1} cinderclient.tests.unit.test_shell.ShellTest.test_dash_dash_help_on_subcommand_2___help_backup_create [0.043289s] ... ok
{3} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_invalid_version_strings_06_5__3 [0.001118s] ... ok
{3} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_invalid_version_strings_08_02_1 [0.005533s] ... ok
{3} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_version_comparisons [0.002769s] ... ok
{3} cinderclient.tests.unit.test_api_versions.DiscoverVersionTestCase.test_microversion_06___3_5____3_7____3_0____3_8____3_9___False___3_7__ [0.001057s] ... ok
{3} cinderclient.tests.unit.test_auth_plugins.CinderNoAuthPluginTest.test_auth_token [0.000446s] ... ok
{3} cinderclient.tests.unit.test_client.GetAPIVersionTestCase.test_get_highest_client_server_version_2_3_40 [0.001669s] ... ok
{6} cinderclient.tests.unit.test_client.GetAPIVersionTestCase.test_get_server_version_cert [0.000803s] ... ok
{3} cinderclient.tests.unit.test_exceptions.ExceptionsTest.test_from_response_overlimit [0.047664s] ... ok
{6} cinderclient.tests.unit.test_client.GetAPIVersionTestCase.test_get_server_version_insecure [0.017426s] ... ok
{6} cinderclient.tests.unit.test_http.ClientTest.test_auth_failure [0.000760s] ... ok
{6} cinderclient.tests.unit.test_http.ClientTest.test_os_endpoint_url [0.000448s] ... ok
{3} cinderclient.tests.unit.test_exceptions.ExceptionsTest.test_from_response_overlimit_gmt [0.002563s] ... ok
{6} cinderclient.tests.unit.test_http.ClientTest.test_rate_limit [0.002944s] ... ok
{3} cinderclient.tests.unit.test_http.ClientTest.test_get_no_retry_400 [0.002341s] ... ok
usage: run.py
{3} cinderclient.tests.unit.test_http.ClientTest.test_retry_limit [0.001209s] ... ok
error: ambiguous option: --test could match --test-parameter, --test_parameter
error: ambiguous option: --test could match --test-parameter, --test_parameter
Try 'run.py help ' for more information.
Try 'run.py help ' for more information.
Try 'run.py help ' for more information.
{6} cinderclient.tests.unit.test_shell.CinderClientArgumentParserTest.test_raise_ambiguity_error_two_hidden_argument [0.001807s] ... ok
{6} cinderclient.tests.unit.test_shell.CinderClientArgumentParserTest.test_raise_ambiguity_error_two_hidden_argument [0.001807s] ... ok
{6} cinderclient.tests.unit.test_shell.CinderClientArgumentParserTest.test_raise_ambiguity_error_two_hidden_argument [0.001807s] ... ok
{3} cinderclient.tests.unit.test_shell.ShellTest.test_auth_system_env [0.012320s] ... ok
{3} cinderclient.tests.unit.test_shell.ShellTest.test_auth_system_env [0.012320s] ... ok
{3} cinderclient.tests.unit.test_shell.ShellTest.test_auth_system_env [0.012320s] ... ok
{1} cinderclient.tests.unit.test_shell.ShellTest.test_help_unknown_command [0.057959s] ... ok
{1} cinderclient.tests.unit.test_shell.ShellTest.test_help_unknown_command [0.057959s] ... ok
{1} cinderclient.tests.unit.test_shell.ShellTest.test_help_unknown_command [0.057959s] ... ok
{1} cinderclient.tests.unit.test_shell.ShellTest.test_version_discovery [0.005808s] ... ok
{1} cinderclient.tests.unit.test_shell.ShellTest.test_version_discovery [0.005808s] ... ok
{1} cinderclient.tests.unit.test_shell.ShellTest.test_version_discovery [0.005808s] ... ok
{1} cinderclient.tests.unit.test_shell.TestLoadVersionedActions.test_load_versioned_actions_v3_0 [0.001615s] ... ok
{1} cinderclient.tests.unit.test_shell.TestLoadVersionedActions.test_load_versioned_actions_v3_0 [0.001615s] ... ok
{1} cinderclient.tests.unit.test_shell.TestLoadVersionedActions.test_load_versioned_actions_v3_0 [0.001615s] ... ok
{1} cinderclient.tests.unit.test_utils.FindResourceTestCase.test_find_by_group_id [0.000785s] ... ok
{1} cinderclient.tests.unit.test_utils.FindResourceTestCase.test_find_by_group_id [0.000785s] ... ok
{1} cinderclient.tests.unit.test_utils.FindResourceTestCase.test_find_by_group_id [0.000785s] ... ok
{1} cinderclient.tests.unit.test_utils.FindResourceTestCase.test_find_by_integer_id [0.000416s] ... ok
{1} cinderclient.tests.unit.test_utils.FindResourceTestCase.test_find_by_integer_id [0.000416s] ... ok
{1} cinderclient.tests.unit.test_utils.FindResourceTestCase.test_find_by_integer_id [0.000416s] ... ok
{1} cinderclient.tests.unit.test_utils.FindResourceTestCase.test_find_by_uuid [0.000418s] ... ok
{1} cinderclient.tests.unit.test_utils.FindResourceTestCase.test_find_by_uuid [0.000418s] ... ok
{1} cinderclient.tests.unit.test_utils.FindResourceTestCase.test_find_by_uuid [0.000418s] ... ok
Exception ignored in: <function Session.__del__ at 0x7fdacf3e9440>
Exception ignored in: <function Session.__del__ at 0x7fdacf3e9440>
Exception ignored in: <function Session.__del__ at 0x7fdacf3e9440>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3/site-packages/keystoneauth1/session.py", line 429, in __del__
  File "/usr/lib/python3/site-packages/keystoneauth1/session.py", line 429, in __del__
    if self._session:
    if self._session:
       ^^^^^^^^^^^^^
       ^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute '_session'
AttributeError: 'Session' object has no attribute '_session'
{1} cinderclient.tests.unit.v3.test_auth.AuthenticationTests.test_authenticate_failure [0.001175s] ... ok
{1} cinderclient.tests.unit.v3.test_auth.AuthenticationTests.test_authenticate_failure [0.001175s] ... ok
{1} cinderclient.tests.unit.v3.test_cgsnapshots.cgsnapshotsTest.test_list_cgsnapshot_with_search_opts [0.000806s] ... ok
{1} cinderclient.tests.unit.v3.test_cgsnapshots.cgsnapshotsTest.test_list_cgsnapshot_with_search_opts [0.000806s] ... ok
{1} cinderclient.tests.unit.v3.test_consistencygroups.ConsistencygroupsTest.test_create_consistencygroup_with_volume_types [0.000571s] ... ok
{1} cinderclient.tests.unit.v3.test_consistencygroups.ConsistencygroupsTest.test_create_consistencygroup_with_volume_types [0.000571s] ... ok
{1} cinderclient.tests.unit.v3.test_consistencygroups.ConsistencygroupsTest.test_update_consistencygroup_description [0.000704s] ... ok
{1} cinderclient.tests.unit.v3.test_consistencygroups.ConsistencygroupsTest.test_update_consistencygroup_description [0.000704s] ... ok
{1} cinderclient.tests.unit.v3.test_consistencygroups.ConsistencygroupsTest.test_update_consistencygroup_name [0.001162s] ... ok
{1} cinderclient.tests.unit.v3.test_consistencygroups.ConsistencygroupsTest.test_update_consistencygroup_name [0.001162s] ... ok
{7} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_invalid_version_strings_05_5__3 [0.002071s] ... ok
{7} cinderclient.tests.unit.test_shell.CinderClientArgumentParserTest.test_ambiguity_solved_for_one_visible_argument [0.001536s] ... ok
WARNING:cinderclient.shell:API version 3.71 requested, 
WARNING:cinderclient.shell:downgrading to 3.16 based on server support.
WARNING:cinderclient.shell:downgrading to 3.16 based on server support.
{0} cinderclient.tests.unit.test_base.BaseTest.test_findall_invalid_attribute [0.003930s] ... ok
{0} cinderclient.tests.unit.test_base.BaseTest.test_findall_invalid_attribute [0.003930s] ... ok
{0} cinderclient.tests.unit.test_base.BaseTest.test_to_dict [0.000579s] ... ok
{0} cinderclient.tests.unit.test_base.BaseTest.test_to_dict [0.000579s] ... ok
{0} cinderclient.tests.unit.test_base.BaseTest.test_to_dict [0.000579s] ... ok
{4} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_invalid_version_strings_01_2 [0.001024s] ... ok
{4} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_invalid_version_strings_01_2 [0.001024s] ... ok
{4} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_invalid_version_strings_01_2 [0.001024s] ... ok
{4} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_invalid_version_strings_02_200 [0.005578s] ... ok
{4} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_invalid_version_strings_02_200 [0.005578s] ... ok
{4} cinderclient.tests.unit.test_api_versions.APIVersionTestCase.test_invalid_version_strings_02_200 [0.005578s] ... ok
{4} cinderclient.tests.unit.test_api_versions.DiscoverVersionTestCase.test_microversion_01___3_1____3_3____3_4____3_7____3_3___True_ [0.001415s] ... ok
{4} cinderclient.tests.unit.test_api_versions.DiscoverVersionTestCase.test_microversion_01___3_1____3_3____3_4____3_7____3_3___True_ [0.001415s] ... ok
{4} cinderclient.tests.unit.test_api_versions.DiscoverVersionTestCase.test_microversion_01___3_1____3_3____3_4____3_7____3_3___True_ [0.001415s] ... ok
{4} cinderclient.tests.unit.test_api_versions.DiscoverVersionTestCase.test_microversion_10___3_5____3_5____3_0____3_5____1_0___True_ [0.008610s] ... ok
{4} cinderclient.tests.unit.test_api_versions.DiscoverVersionTestCase.test_microversion_10___3_5____3_5____3_0____3_5____1_0___True_ [0.008610s] ... ok
{4} cinderclient.tests.unit.test_api_versions.DiscoverVersionTestCase.test_microversion_10___3_5____3_5____3_0____3_5____1_0___True_ [0.008610s] ... ok
{1} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_create_4 [0.058258s] ... ok
{1} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_create_4 [0.058258s] ... ok
{1} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_create_4 [0.058258s] ... ok
{6} cinderclient.tests.unit.test_shell.ShellTest.test_password_prompted [0.068268s] ... FAILED
{6} cinderclient.tests.unit.test_shell.ShellTest.test_password_prompted [0.068268s] ... FAILED
{6} cinderclient.tests.unit.test_shell.ShellTest.test_password_prompted [0.068268s] ... FAILED



Captured traceback:
Captured traceback:
Captured traceback:
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
    Traceback (most recent call last):
    Traceback (most recent call last):



      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_shell.py", line 245, in test_password_prompted
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_shell.py", line 245, in test_password_prompted
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_shell.py", line 245, in test_password_prompted
    self.assertRaises(ks_exc.ConnectFailure, _shell.main, ['list'])
    self.assertRaises(ks_exc.ConnectFailure, _shell.main, ['list'])


      File "/usr/lib/python3/site-packages/testtools/testcase.py", line 495, in assertRaises
    self.assertThat(our_callable, matcher)
  warnings.warn(
{7} cinderclient.tests.unit.v3.test_capabilities.CapabilitiesTest.test___repr__ [0.001975s] ... ok
{7} cinderclient.tests.unit.v3.test_clusters.ClusterTest.test_cluster_show [0.000714s] ... ok
{7} cinderclient.tests.unit.v3.test_clusters.ClusterTest.test_cluster_show [0.000714s] ... ok
{7} cinderclient.tests.unit.v3.test_clusters.ClusterTest.test_clusters_list_2_False [0.002960s] ... ok
{7} cinderclient.tests.unit.v3.test_clusters.ClusterTest.test_clusters_list_2_False [0.002960s] ... ok
{7} cinderclient.tests.unit.v3.test_clusters.ClusterTest.test_clusters_list_num_down_hosts_1_True [0.000670s] ... ok
{7} cinderclient.tests.unit.v3.test_clusters.ClusterTest.test_clusters_list_num_down_hosts_1_True [0.000670s] ... ok
{7} cinderclient.tests.unit.v3.test_clusters.ClusterTest.test_clusters_list_num_down_hosts_1_True [0.000670s] ... ok
{6} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_create_5 [0.059878s] ... ok
{6} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_create_5 [0.059878s] ... ok
{6} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_create_5 [0.059878s] ... ok
{7} cinderclient.tests.unit.v3.test_clusters.ClusterTest.test_clusters_list_num_down_hosts_2_False [0.000643s] ... ok
{7} cinderclient.tests.unit.v3.test_clusters.ClusterTest.test_clusters_list_num_down_hosts_2_False [0.000643s] ... ok
{7} cinderclient.tests.unit.v3.test_clusters.ClusterTest.test_clusters_list_num_down_hosts_2_False [0.000643s] ... ok
WARNING:cinderclient.shell:API version 3.71 requested, 
WARNING:cinderclient.shell:API version 3.71 requested, 
WARNING:cinderclient.shell:API version 3.71 requested, 
WARNING:cinderclient.shell:downgrading to 3.16 based on server support.
WARNING:cinderclient.shell:downgrading to 3.16 based on server support.
WARNING:cinderclient.shell:downgrading to 3.16 based on server support.
{7} cinderclient.tests.unit.v3.test_consistencygroups.ConsistencygroupsTest.test_list_consistencygroup_with_empty_search_opt [0.002503s] ... ok
{7} cinderclient.tests.unit.v3.test_consistencygroups.ConsistencygroupsTest.test_list_consistencygroup_with_empty_search_opt [0.002503s] ... ok
{7} cinderclient.tests.unit.v3.test_consistencygroups.ConsistencygroupsTest.test_list_consistencygroup_with_empty_search_opt [0.002503s] ... ok
{2} cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method [0.008396s] ... FAILED
{2} cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method [0.008396s] ... FAILED
{2} cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method [0.008396s] ... FAILED



Captured traceback:
Captured traceback:
Captured traceback:
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
    Traceback (most recent call last):
    Traceback (most recent call last):



      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 149, in test_sessionclient_request_method
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 149, in test_sessionclient_request_method
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 149, in test_sessionclient_request_method
    response, body = session_client.request(mock.sentinel.url,
    response, body = session_client.request(mock.sentinel.url,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/client.py", line 196, in request

{3} cinderclient.tests.unit.test_shell.ShellTest.test_cinder_service_name [0.203380s] ... ok
{7} cinderclient.tests.unit.v3.test_group_snapshots.GroupSnapshotsTest.test_update_group_snapshot [0.000709s] ... ok
{7} cinderclient.tests.unit.v3.test_group_snapshots.GroupSnapshotsTest.test_update_group_snapshot [0.000709s] ... ok
{7} cinderclient.tests.unit.v3.test_group_types.GroupTypesTest.test_create_non_public [0.000502s] ... ok
{7} cinderclient.tests.unit.v3.test_group_types.GroupTypesTest.test_create_non_public [0.000502s] ... ok
{7} cinderclient.tests.unit.v3.test_group_types.GroupTypesTest.test_list_group_types [0.001588s] ... ok
{7} cinderclient.tests.unit.v3.test_group_types.GroupTypesTest.test_list_group_types [0.001588s] ... ok
{7} cinderclient.tests.unit.v3.test_group_types.GroupTypesTest.test_list_group_types [0.001588s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_create_group_from_src_snap [0.000712s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_create_group_from_src_snap [0.000712s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_create_group_from_src_snap [0.000712s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_delete_group [0.000633s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_delete_group [0.000633s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_delete_group [0.000633s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_disable_replication_group [0.000636s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_disable_replication_group [0.000636s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_disable_replication_group [0.000636s] ... ok
{2} cinderclient.tests.unit.test_client.ClientTestSensitiveInfo.test_resp_does_not_log_sensitive_info [0.007040s] ... ok
{2} cinderclient.tests.unit.test_client.ClientTestSensitiveInfo.test_resp_does_not_log_sensitive_info [0.007040s] ... ok
{2} cinderclient.tests.unit.test_client.ClientTestSensitiveInfo.test_resp_does_not_log_sensitive_info [0.007040s] ... ok
{2} cinderclient.tests.unit.test_client.GetAPIVersionTestCase.test_get_highest_client_server_version_negative [0.001273s] ... ok
{2} cinderclient.tests.unit.test_client.GetAPIVersionTestCase.test_get_highest_client_server_version_negative [0.001273s] ... ok
{2} cinderclient.tests.unit.test_client.GetAPIVersionTestCase.test_get_highest_client_server_version_negative [0.001273s] ... ok
{5} cinderclient.tests.unit.test_client.ClientTest.test_keystone_request_raises_auth_failure_exception [0.008431s] ... FAILED
{5} cinderclient.tests.unit.test_client.ClientTest.test_keystone_request_raises_auth_failure_exception [0.008431s] ... FAILED
{5} cinderclient.tests.unit.test_client.ClientTest.test_keystone_request_raises_auth_failure_exception [0.008431s] ... FAILED



Captured traceback:
Captured traceback:
Captured traceback:
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
    Traceback (most recent call last):
    Traceback (most recent call last):



      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 240, in test_keystone_request_raises_auth_failure_exception
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 240, in test_keystone_request_raises_auth_failure_exception
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 240, in test_keystone_request_raises_auth_failure_exception
    self.assertRaises(keystone_exception.AuthorizationFailure,
    self.assertRaises(keystone_exception.AuthorizationFailure,


      File "/usr/lib/python3/site-packages/testtools/testcase.py", line 495, in assertRaises
    self.assertThat(our_callable, matcher)
    TypeError: '>=' not supported between instances of 'Mock' and 'int'

{2} cinderclient.tests.unit.test_client.GetAPIVersionTestCase.test_get_server_version_2_https___192_168_122_127_8776_v3_e55285ebd741b1819393f772f11fc3 [0.000771s] ... ok
{2} cinderclient.tests.unit.test_client.GetAPIVersionTestCase.test_get_server_version_2_https___192_168_122_127_8776_v3_e55285ebd741b1819393f772f11fc3 [0.000771s] ... ok
{2} cinderclient.tests.unit.test_http.ClientTest.test_auth_with_keystone_v3 [0.000841s] ... ok
{2} cinderclient.tests.unit.test_http.ClientTest.test_auth_with_keystone_v3 [0.000841s] ... ok
{2} cinderclient.tests.unit.test_http.ClientTest.test_get_reauth_0_retries [0.000945s] ... ok
{2} cinderclient.tests.unit.test_http.ClientTest.test_get_reauth_0_retries [0.000945s] ... ok
{2} cinderclient.tests.unit.test_http.ClientTest.test_get_reauth_0_retries [0.000945s] ... ok
{2} cinderclient.tests.unit.test_http.ClientTest.test_get_retry_400_socket [0.001000s] ... ok
{2} cinderclient.tests.unit.test_http.ClientTest.test_get_retry_400_socket [0.001000s] ... ok
{2} cinderclient.tests.unit.test_http.ClientTest.test_get_retry_400_socket [0.001000s] ... ok
{2} cinderclient.tests.unit.test_http.ClientTest.test_post [0.000748s] ... ok
{2} cinderclient.tests.unit.test_http.ClientTest.test_post [0.000748s] ... ok
{2} cinderclient.tests.unit.test_http.ClientTest.test_post [0.000748s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_update_group_name_2 [0.010573s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_update_group_name_2 [0.010573s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_update_group_name_2 [0.010573s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_update_group_name_3 [0.000877s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_update_group_name_3 [0.000877s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_update_group_name_3 [0.000877s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_update_group_no_props [0.000441s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_update_group_no_props [0.000441s] ... ok
{7} cinderclient.tests.unit.v3.test_groups.GroupsTest.test_update_group_no_props [0.000441s] ... ok
{5} cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method_raises_overlimit [0.001765s] ... FAILED
{5} cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method_raises_overlimit [0.001765s] ... FAILED
{5} cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method_raises_overlimit [0.001765s] ... FAILED



Captured traceback:
Captured traceback:
Captured traceback:
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
    Traceback (most recent call last):
    Traceback (most recent call last):



      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 216, in test_sessionclient_request_method_raises_overlimit
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 216, in test_sessionclient_request_method_raises_overlimit
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 216, in test_sessionclient_request_method_raises_overlimit
    self.assertRaises(exceptions.OverLimit, session_client.request,
    self.assertRaises(exceptions.OverLimit, session_client.request,


      File "/usr/lib/python3/site-packages/testtools/testcase.py", line 495, in assertRaises
    self.assertThat(our_callable, matcher)
{5} cinderclient.tests.unit.test_http.ClientTest.test_get_no_auth_url [0.000465s] ... ok
{7} cinderclient.tests.unit.v3.test_limits.TestAbsoluteLimit.test_equal [0.000515s] ... ok
{7} cinderclient.tests.unit.v3.test_limits.TestAbsoluteLimit.test_equal [0.000515s] ... ok
{7} cinderclient.tests.unit.v3.test_limits.TestAbsoluteLimit.test_not_equal_values [0.000432s] ... ok
{7} cinderclient.tests.unit.v3.test_limits.TestAbsoluteLimit.test_not_equal_values [0.000432s] ... ok
{1} cinderclient.tests.unit.v3.test_shell.ShellTest.test_default_type_list [0.047663s] ... ok
{1} cinderclient.tests.unit.v3.test_shell.ShellTest.test_default_type_list [0.047663s] ... ok
{5} cinderclient.tests.unit.test_shell.ShellTest.test_duplicate_filters [0.002099s] ... ok
{5} cinderclient.tests.unit.test_shell.ShellTest.test_duplicate_filters [0.002099s] ... ok
{7} cinderclient.tests.unit.v3.test_limits.TestLimits.test_absolute [0.000452s] ... ok
{7} cinderclient.tests.unit.v3.test_limits.TestLimits.test_absolute [0.000452s] ... ok
{7} cinderclient.tests.unit.v3.test_messages.MessagesTest.test_list_messages [0.002758s] ... ok
{7} cinderclient.tests.unit.v3.test_messages.MessagesTest.test_list_messages [0.002758s] ... ok
{7} cinderclient.tests.unit.v3.test_quota_classes.QuotaClassSetsTest.test_class_quotas_get [0.000493s] ... ok
{7} cinderclient.tests.unit.v3.test_quota_classes.QuotaClassSetsTest.test_class_quotas_get [0.000493s] ... ok
{7} cinderclient.tests.unit.v3.test_resource_filters.ResourceFilterTests.test_list_resource_filters_2 [0.000471s] ... ok
{7} cinderclient.tests.unit.v3.test_resource_filters.ResourceFilterTests.test_list_resource_filters_2 [0.000471s] ... ok
{7} cinderclient.tests.unit.v3.test_services_base.ServicesTest.test_list_services_with_binary [0.000525s] ... ok
{7} cinderclient.tests.unit.v3.test_services_base.ServicesTest.test_list_services_with_binary [0.000525s] ... ok
Exception ignored in: <function Session.__del__ at 0x7f0cdd80d440>
Exception ignored in: <function Session.__del__ at 0x7f0cdd80d440>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3/site-packages/keystoneauth1/session.py", line 429, in __del__
  File "/usr/lib/python3/site-packages/keystoneauth1/session.py", line 429, in __del__
    if self._session:
    if self._session:
       ^^^^^^^^^^^^^
       ^^^^^^^^^^^^^
AttributeError: 'Session' object has no attribute '_session'
AttributeError: 'Session' object has no attribute '_session'
{3} cinderclient.tests.unit.test_shell.ShellTest.test_http_client_with_cert_and_key [0.041090s] ... ok
{3} cinderclient.tests.unit.test_shell.ShellTest.test_http_client_with_cert_and_key [0.041090s] ... ok
{2} cinderclient.tests.unit.test_shell.ShellTest.test_dash_dash_help_on_subcommand_1_backup_create___help [0.045148s] ... ok
{2} cinderclient.tests.unit.test_shell.ShellTest.test_dash_dash_help_on_subcommand_1_backup_create___help [0.045148s] ... ok
{2} cinderclient.tests.unit.test_shell.TestLoadVersionedActions.test_load_versioned_actions_with_args2 [0.001541s] ... ok
{2} cinderclient.tests.unit.test_shell.TestLoadVersionedActions.test_load_versioned_actions_with_args2 [0.001541s] ... ok
{6} cinderclient.tests.unit.v3.test_shell.ShellTest.test_backup_list_with_with_count [0.061215s] ... ok
{6} cinderclient.tests.unit.v3.test_shell.ShellTest.test_backup_list_with_with_count [0.061215s] ... ok
{2} cinderclient.tests.unit.test_shell.TestLoadVersionedActions.test_load_versioned_actions_with_help [0.002346s] ... ok
{2} cinderclient.tests.unit.test_shell.TestLoadVersionedActions.test_load_versioned_actions_with_help [0.002346s] ... ok
{2} cinderclient.tests.unit.test_utils.BuildQueryParamTestCase.test_build_param_with_nones_3 [0.000556s] ... ok
              [--os-project-domain-name OS_PROJECT_DOMAIN_NAME]
              [--os-trust-id OS_TRUST_ID]
              [--os-default-domain-id OS_DEFAULT_DOMAIN_ID]
              [--os-default-domain-name OS_DEFAULT_DOMAIN_NAME]
              [--os-user-id OS_USER_ID] [--os-username OS_USERNAME]
              [--os-user-domain-id OS_USER_DOMAIN_ID]
              [--os-user-domain-name OS_USER_DOMAIN_NAME]
              [--os-password OS_PASSWORD] [--os-auth-strategy <auth-strategy>]
              [--os-url <url>]
              <subcommand> ...
error: argument <subcommand>: invalid choice: 'backup-update'
Try 'cinder help ' for more information.
{6} cinderclient.tests.unit.v3.test_shell.ShellTest.test_backup_update_wrong_version [0.069233s] ... ok
{4} cinderclient.tests.unit.v3.test_clusters.ClusterTest.test_clusters_list_1_True [0.000688s] ... ok
{4} cinderclient.tests.unit.v3.test_consistencygroups.ConsistencygroupsTest.test_update_consistencygroup_none [0.000454s] ... ok
{4} cinderclient.tests.unit.v3.test_group_snapshots.GroupSnapshotsTest.test_delete_group_snapshot [0.000943s] ... ok
{4} cinderclient.tests.unit.v3.test_group_snapshots.GroupSnapshotsTest.test_get_group_snapshot [0.000945s] ... ok
{5} cinderclient.tests.unit.test_shell.ShellTest.test_help_on_subcommand [0.110073s] ... ok
{4} cinderclient.tests.unit.v3.test_group_types.GroupTypesTest.test_default [0.000673s] ... ok
{2} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_create_with_mode_5 [0.046680s] ... ok
{4} cinderclient.tests.unit.v3.test_group_types.GroupTypesTest.test_delete [0.000624s] ... ok
{5} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_create_with_mode_2 [0.079766s] ... ok
{6} cinderclient.tests.unit.v3.test_shell.ShellTest.test_group_create_from_src_2 [0.094332s] ... ok
DEBUG:keystoneauth.session:REQ: curl -g -i -X GET http://keystone.example.com:5000/ -H "Accept: application/json" -H "User-Agent: run.py keystoneauth1/5.10.0 python-requests/2.32.3 CPython/3.12.10"
DEBUG:keystoneauth.session:RESP: [200] Content-Type: application/json
DEBUG:keystoneauth.session:RESP BODY: {"versions": {"values": [{"id": "v3.0", "links": [{"href": "http://keystone.example.com:5000/v3", "rel": "self"}], "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}, {"base": "application/xml", "type": "application/vnd.openstack.identity-v3+xml"}], "status": "stable", "updated": "2013-03-06T00:00:00Z"}, {"id": "v2.0", "links": [{"href": "http://keystone.example.com:5000/v2.0", "rel": "self"}, {"href": "http://docs.openstack.org/api/openstack-identity-service/2.0/content/", "rel": "describedby", "type": "text/html"}, {"href": "http://docs.openstack.org/api/openstack-identity-service/2.0/identity-dev-guide-2.0.pdf", "rel": "describedby", "type": "application/pdf"}], "status": "stable", "updated": "2013-03-06T00:00:00Z"}]}}
{3} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_list_7 [0.039209s] ... ok
{7} cinderclient.tests.unit.v3.test_shell.ShellTest.test_backup_with_az [0.111423s] ... ok
{1} cinderclient.tests.unit.v3.test_shell.ShellTest.test_group_update_invalid_args [0.070176s] ... ok
usage: cinder backup-update [--name [<name>]] [--description <description>]
                            <backup>
error: the following arguments are required: <backup>
Try 'cinder help backup-update' for more information.
{3} cinderclient.tests.unit.v3.test_shell.ShellTest.test_backup_update_without_arguments [0.034772s] ... ok
{4} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_list_1 [0.105715s] ... ok
{2} cinderclient.tests.unit.v3.test_shell.ShellTest.test_create_volume_with_backup_2 [0.075100s] ... ok
{0} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_create_with_mode_1 [0.092453s] ... ok
{5} cinderclient.tests.unit.v3.test_shell.ShellTest.test_attachment_create_with_mode_4 [0.089851s] ... ok
DEBUG:keystoneauth.session:REQ: curl -g -i -X GET http://keystone.example.com:5000/ -H "Accept: application/json" -H "User-Agent: run.py keystoneauth1/5.10.0 python-requests/2.32.3 CPython/3.12.10"
DEBUG:keystoneauth.session:RESP: [200] Content-Type: application/json
DEBUG:keystoneauth.session:RESP BODY: {"versions": {"values": [{"id": "v3.0", "links": [{"href": "http://keystone.example.com:5000/v3", "rel": "self"}], "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v3+json"}, {"base": "application/xml", "type": "application/vnd.openstack.identity-v3+xml"}], "status": "stable", "updated": "2013-03-06T00:00:00Z"}, {"id": "v2.0", "links": [{"href": "http://keystone.example.com:5000/v2.0", "rel": "self"}, {"href": "http://docs.openstack.org/api/openstack-identity-service/2.0/content/", "rel": "describedby", "type": "text/html"}, {"href": "http://docs.openstack.org/api/openstack-identity-service/2.0/identity-dev-guide-2.0.pdf", "rel": "describedby", "type": "application/pdf"}], "status": "stable", "updated": "2013-03-06T00:00:00Z"}]}}
{3} cinderclient.tests.unit.v3.test_shell.ShellTest.test_backup_with_metadata [0.046229s] ... ok
              [--os-project-domain-name OS_PROJECT_DOMAIN_NAME]
              [--os-trust-id OS_TRUST_ID]
              [--os-default-domain-id OS_DEFAULT_DOMAIN_ID]
              [--os-default-domain-name OS_DEFAULT_DOMAIN_NAME]
              [--os-user-id OS_USER_ID] [--os-username OS_USERNAME]
              [--os-user-domain-id OS_USER_DOMAIN_ID]
              [--os-user-domain-name OS_USER_DOMAIN_NAME]
              [--os-password OS_PASSWORD] [--os-auth-strategy <auth-strategy>]
              [--os-url <url>]
              <subcommand> ...
error: argument <subcommand>: invalid choice: 'service-set-log'
Try 'cinder help ' for more information.
{1} cinderclient.tests.unit.v3.test_shell.ShellTest.test_snapshot_create_3_66_with_force_not_true_3_no [0.048898s] ... ok
{3} cinderclient.tests.unit.v3.test_shell.ShellTest.test_service_set_log_before_3_32 [0.087485s] ... ok
{0} cinderclient.tests.unit.v3.test_shell.ShellTest.test_restore_with_az [0.081043s] ... ok
{7} cinderclient.tests.unit.v3.test_shell.ShellTest.test_migrate_volume_bool_force [0.075267s] ... ok
{6} cinderclient.tests.unit.v3.test_shell.ShellTest.test_list_with_group_id_after_3_10_1_3_10 [0.076811s] ... ok
{5} cinderclient.tests.unit.v3.test_shell.ShellTest.test_list_with_filters_mixed_18 [0.062207s] ... ok
{1} cinderclient.tests.unit.v3.test_shell.ShellTest.test_snapshot_create_3_66_with_force_not_true_5_whatever [0.051365s] ... ok
{7} cinderclient.tests.unit.v3.test_shell.ShellTest.test_migrate_volume_cluster [0.058974s] ... ok
{2} cinderclient.tests.unit.v3.test_shell.ShellTest.test_service_set_log_levels_1__ [0.077423s] ... ok
              [--os-project-domain-name OS_PROJECT_DOMAIN_NAME]
              [--os-trust-id OS_TRUST_ID]
              [--os-default-domain-id OS_DEFAULT_DOMAIN_ID]
              [--os-default-domain-name OS_DEFAULT_DOMAIN_NAME]
              [--os-user-id OS_USER_ID] [--os-username OS_USERNAME]
              [--os-user-domain-id OS_USER_DOMAIN_ID]
              [--os-user-domain-name OS_USER_DOMAIN_NAME]
              [--os-password OS_PASSWORD] [--os-auth-strategy <auth-strategy>]
              [--os-url <url>]
              <subcommand> ...
error: argument <subcommand>: invalid choice: 'service-get-log'
Try 'cinder help ' for more information.
{6} cinderclient.tests.unit.v3.test_shell.ShellTest.test_service_get_log_before_3_32 [0.075738s] ... ok
{0} cinderclient.tests.unit.v3.test_shell.ShellTest.test_snapshot_list_with_metadata [0.093353s] ... ok
{4} cinderclient.tests.unit.v3.test_shell.ShellTest.test_reset_state_entity_not_found_3_snapshot [0.065062s] ... ok
{2} cinderclient.tests.unit.v3.test_shell.ShellTest.test_volume_manageable_list_details [0.073148s] ... ok
{2} cinderclient.tests.unit.v3.test_types.TypesTest.test_get [0.000618s] ... ok
{2} cinderclient.tests.unit.v3.test_volume_backups_30.VolumeBackupsTest.test_create_full [0.000529s] ... ok
{2} cinderclient.tests.unit.v3.test_volume_backups_30.VolumeBackupsTest.test_delete [0.000698s] ... ok
{2} cinderclient.tests.unit.v3.test_volume_backups_30.VolumeBackupsTest.test_list_with_pagination [0.000528s] ... ok
{7} cinderclient.tests.unit.v3.test_shell.ShellTest.test_type_list_private [0.088955s] ... ok
+------+-----------+---------------+------+-------------+----------+-------------+
| 1234 | available | sample-volume | 1    | None        | false    | 1234        |
+------+-----------+---------------+------+-------------+----------+-------------+
+--------------------------------------+--------------------------------------+-----------+--------+------+--------------+---------------+
| ID                                   | Volume ID                            | Status    | Name   | Size | Object Count | Container     |
+--------------------------------------+--------------------------------------+-----------+--------+------+--------------+---------------+
| 76a17945-3c6f-435c-975b-b5685db10b62 | 712f4980-5ac1-41e5-9383-390aa7c9f58b | available | backup | 10   | 220          | volumebackups |
| d09534c6-08b8-4441-9e87-8976f3a8f699 | 712f4980-5ac1-41e5-9383-390aa7c9f58b | available | backup | 10   | 220          | volumebackups |
+--------------------------------------+--------------------------------------+-----------+--------+------+--------------+---------------+
Request to migrate volume 1234 has been accepted.
Migration for volume 1234 failed: .
Called unknown API method: GET /backups/999999, expected fakes method name: get_backups_999999
+---------------------+----------------------------+
| Property            | Value                      |
+---------------------+----------------------------+
| created_at          | 2012-08-28T16:30:31.000000 |
| display_description | None                       |
| display_name        | None                       |
| id                  | 1234                       |
| metadata            | {}                         |
| size                | 1                          |
| 12345 |               |               | VOLUME_000002 | Fake Message |
+-------+---------------+---------------+---------------+--------------+
+----------+-------------------------+
| Property | Value                   |
+----------+-------------------------+
| name     | ubuntu@lvm#backend_name |
+----------+-------------------------+
+-------------------+-------+
| Property          | Value |
+-------------------+-------+
| not_default_field | error |
+-------------------+-------+
+-------------+-------------+
| Property    | Value       |
+-------------+-------------+
| backup_id   | 1234        |
| volume_id   | 1234        |
| volume_name | restore_vol |
+-------------+-------------+
+-------------+-------------+
| Property    | Value       |
              [--os-project-domain-name OS_PROJECT_DOMAIN_NAME]
              [--os-trust-id OS_TRUST_ID]
              [--os-default-domain-id OS_DEFAULT_DOMAIN_ID]
              [--os-default-domain-name OS_DEFAULT_DOMAIN_NAME]
              [--os-user-id OS_USER_ID] [--os-username OS_USERNAME]
              [--os-user-domain-id OS_USER_DOMAIN_ID]
              [--os-user-domain-name OS_USER_DOMAIN_NAME]
              [--os-password OS_PASSWORD] [--os-auth-strategy <auth-strategy>]
              [--os-url <url>]
              <subcommand> ...
error: argument <subcommand>: invalid choice: 'work-cleanup'
Try 'cinder help ' for more information.
{0} cinderclient.tests.unit.v3.test_shell.ShellTest.test_worker_cleanup_before_3_24 [0.077980s] ... ok
{0} cinderclient.tests.unit.v3.test_volume_backups.VolumesTest.test_restore_with_name [0.000788s] ... ok
{0} cinderclient.tests.unit.v3.test_volume_backups.VolumesTest.test_update [0.000824s] ... ok
{0} cinderclient.tests.unit.v3.test_volume_backups_30.VolumeBackupsTest.test_create [0.000885s] ... ok
{0} cinderclient.tests.unit.v3.test_volume_backups_30.VolumeBackupsTest.test_force_delete_with_True_force_param_value [0.000565s] ... ok
{0} cinderclient.tests.unit.v3.test_volumes.VolumesTest.test_create_volume_with_hint [0.000603s] ... ok
{0} cinderclient.tests.unit.v3.test_volumes.VolumesTest.test_volume_list_manageable_detailed [0.003693s] ... ok
{0} cinderclient.tests.unit.v3.test_volumes_base.FormatSortParamTestCase.test_format_sort_string_single_key_and_dir [0.002021s] ... ok
{0} cinderclient.tests.unit.v3.test_volumes_base.VolumesTest.test_delete_volume [0.000688s] ... ok
{4} cinderclient.tests.unit.v3.test_volumes_base.VolumesTest.test_set_bootable [0.000529s] ... ok

+----------------------------------------------------------------+------+----------------+
| reference                                                      | size | safe_to_manage |
+----------------------------------------------------------------+------+----------------+
| {'source-name': 'volume-ffffffff-0000-ffff-0000-ffffffffffff'} | 4    | False          |
| {'source-name': 'myvol'}                                       | 5    | True           |
| {'source-name': 'myvol'}                                       | 5    | True           |
+----------------------------------------------------------------+------+----------------+
+----------------------------------------------------------------+------+----------------+



==============================
==============================
==============================
Failed 5 tests - output below:
Failed 5 tests - output below:
Failed 5 tests - output below:
==============================
==============================
==============================



cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method_raises_badrequest
cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method_raises_badrequest
cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method_raises_badrequest
--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------



Captured traceback:
Captured traceback:
Captured traceback:
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
    Traceback (most recent call last):
    Traceback (most recent call last):



      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 192, in test_sessionclient_request_method_raises_badrequest
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 192, in test_sessionclient_request_method_raises_badrequest
    self.assertRaises(exceptions.BadRequest, session_client.request,
    self.assertRaises(exceptions.BadRequest, session_client.request,


      File "/usr/lib/python3/site-packages/testtools/testcase.py", line 495, in assertRaises
    self.assertThat(our_callable, matcher)
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/client.py", line 196, in request
    if raise_exc and resp.status_code >= 400:
                     ^^^^^^^^^^^^^^^^^^^^^^^
                     ^^^^^^^^^^^^^^^^^^^^^^^


    TypeError: '>=' not supported between instances of 'Mock' and 'int'
    TypeError: '>=' not supported between instances of 'Mock' and 'int'




cinderclient.tests.unit.test_shell.ShellTest.test_password_prompted
cinderclient.tests.unit.test_shell.ShellTest.test_password_prompted
-------------------------------------------------------------------
-------------------------------------------------------------------


Captured traceback:
Captured traceback:
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
    Traceback (most recent call last):


      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_shell.py", line 245, in test_password_prompted
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_shell.py", line 245, in test_password_prompted
    self.assertRaises(ks_exc.ConnectFailure, _shell.main, ['list'])
    self.assertRaises(ks_exc.ConnectFailure, _shell.main, ['list'])


      File "/usr/lib/python3/site-packages/testtools/testcase.py", line 495, in assertRaises
    self.assertThat(our_callable, matcher)
      File "/usr/lib64/python3.12/urllib/parse.py", line 504, in urlsplit
    if i > 0 and url[0].isascii() and url[0].isalpha():
       ^^^^^
       ^^^^^


    TypeError: '>' not supported between instances of 'MagicMock' and 'int'
    TypeError: '>' not supported between instances of 'MagicMock' and 'int'




cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method
cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


Captured traceback:
Captured traceback:
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
    Traceback (most recent call last):


      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 149, in test_sessionclient_request_method
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 149, in test_sessionclient_request_method
    response, body = session_client.request(mock.sentinel.url,
    response, body = session_client.request(mock.sentinel.url,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/client.py", line 196, in request
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/client.py", line 196, in request
    if raise_exc and resp.status_code >= 400:
                     ^^^^^^^^^^^^^^^^^^^^^^^
                     ^^^^^^^^^^^^^^^^^^^^^^^


    TypeError: '>=' not supported between instances of 'Mock' and 'int'
    TypeError: '>=' not supported between instances of 'Mock' and 'int'




cinderclient.tests.unit.test_client.ClientTest.test_keystone_request_raises_auth_failure_exception
cinderclient.tests.unit.test_client.ClientTest.test_keystone_request_raises_auth_failure_exception
--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------


Captured traceback:
Captured traceback:
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
    Traceback (most recent call last):


      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 240, in test_keystone_request_raises_auth_failure_exception
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 240, in test_keystone_request_raises_auth_failure_exception
    self.assertRaises(keystone_exception.AuthorizationFailure,
    self.assertRaises(keystone_exception.AuthorizationFailure,


      File "/usr/lib/python3/site-packages/testtools/testcase.py", line 495, in assertRaises
    self.assertThat(our_callable, matcher)
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/client.py", line 196, in request
    if raise_exc and resp.status_code >= 400:
                     ^^^^^^^^^^^^^^^^^^^^^^^
                     ^^^^^^^^^^^^^^^^^^^^^^^


    TypeError: '>=' not supported between instances of 'Mock' and 'int'
    TypeError: '>=' not supported between instances of 'Mock' and 'int'




cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method_raises_overlimit
cinderclient.tests.unit.test_client.ClientTest.test_sessionclient_request_method_raises_overlimit
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------


Captured traceback:
Captured traceback:
~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
    Traceback (most recent call last):


      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
      File "/usr/lib64/python3.12/unittest/mock.py", line 1396, in patched
    return func(*newargs, **newkeywargs)
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 216, in test_sessionclient_request_method_raises_overlimit
      File "/usr/src/RPM/BUILD/cinderclient-9.6.0/cinderclient/tests/unit/test_client.py", line 216, in test_sessionclient_request_method_raises_overlimit
    self.assertRaises(exceptions.OverLimit, session_client.request,
    self.assertRaises(exceptions.OverLimit, session_client.request,


      File "/usr/lib/python3/site-packages/testtools/testcase.py", line 495, in assertRaises
    self.assertThat(our_callable, matcher)
    TypeError: '>=' not supported between instances of 'Mock' and 'int'





======
======
Totals
Totals
======
======
Ran: 739 tests in 4.2490 sec.
Ran: 739 tests in 4.2490 sec.
 - Passed: 734
 - Passed: 734
 - Skipped: 0
 - Skipped: 0
 - Expected Fail: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Unexpected Success: 0
 - Failed: 5
 - Failed: 5
Sum of execute time for each test: 23.4815 sec.
Sum of execute time for each test: 23.4815 sec.


==============
==============
Worker Balance
Worker Balance
Worker Balance
==============
==============
==============
 - Worker 0 (93 tests) => 0:00:02.833822
 - Worker 0 (93 tests) => 0:00:02.833822
 - Worker 0 (93 tests) => 0:00:02.833822
 - Worker 1 (93 tests) => 0:00:02.537931
 - Worker 1 (93 tests) => 0:00:02.537931
 - Worker 1 (93 tests) => 0:00:02.537931
 - Worker 2 (93 tests) => 0:00:02.417952
 - Worker 2 (93 tests) => 0:00:02.417952
 - Worker 2 (93 tests) => 0:00:02.417952
 - Worker 3 (92 tests) => 0:00:02.428581
 - Worker 3 (92 tests) => 0:00:02.428581
 - Worker 4 (92 tests) => 0:00:03.970182
 - Worker 4 (92 tests) => 0:00:03.970182
 - Worker 5 (92 tests) => 0:00:03.754861
 - Worker 6 (92 tests) => 0:00:03.123791
 - Worker 6 (92 tests) => 0:00:03.123791
 - Worker 7 (92 tests) => 0:00:02.786014
 - Worker 7 (92 tests) => 0:00:02.786014
error: Bad exit status from /usr/src/tmp/rpm-tmp.14923 (%check)
error: Bad exit status from /usr/src/tmp/rpm-tmp.14923 (%check)




RPM build errors:
RPM build errors:
    Bad exit status from /usr/src/tmp/rpm-tmp.14923 (%check)
    Bad exit status from /usr/src/tmp/rpm-tmp.14923 (%check)
Command exited with non-zero status 1
Command exited with non-zero status 1
24.79user 2.48system 0:16.02elapsed 170%CPU (0avgtext+0avgdata 96312maxresident)k
24.79user 2.48system 0:16.02elapsed 170%CPU (0avgtext+0avgdata 96312maxresident)k
0inputs+0outputs (0major+350804minor)pagefaults 0swaps
0inputs+0outputs (0major+350804minor)pagefaults 0swaps
hsh-rebuild: rebuild of `python3-module-cinderclient-9.6.0-alt1.src.rpm' failed.
hsh-rebuild: rebuild of `python3-module-cinderclient-9.6.0-alt1.src.rpm' failed.
Command exited with non-zero status 1
Command exited with non-zero status 1
7.95user 3.21system 0:41.56elapsed 26%CPU (0avgtext+0avgdata 144068maxresident)k
7.95user 3.21system 0:41.56elapsed 26%CPU (0avgtext+0avgdata 144068maxresident)k
13504inputs+0outputs (0major+362632minor)pagefaults 0swaps
