+ export 'FFLAGS=-pipe -frecord-gcc-switches -Wall -g -O2 -flto=auto'
+ FFLAGS='-pipe -frecord-gcc-switches -Wall -g -O2 -flto=auto'
+ export NO_INTERNET=YES
+ NO_INTERNET=YES
+ /usr/bin/python3 -m pyproject_installer run -- python3 -m pytest
INFO     : Creating venv
INFO     : Installing console scripts
INFO     : Installing console scripts
INFO     : Installing package: /usr/src/RPM/BUILD/django-graphiql-debug-toolbar-0.2.0/dist/django_graphiql_debug_toolbar-0.2.0-py3-none-any.whl
INFO     : Installing package: /usr/src/RPM/BUILD/django-graphiql-debug-toolbar-0.2.0/dist/django_graphiql_debug_toolbar-0.2.0-py3-none-any.whl
INFO     : Running command: ['/usr/src/RPM/BUILD/django-graphiql-debug-toolbar-0.2.0/.run_venv/bin/python3', '-m', 'pyproject_installer', 'install', '/usr/src/RPM/BUILD/django-graphiql-debug-toolbar-0.2.0/dist/django_graphiql_debug_toolbar-0.2.0-py3-none-any.whl']
INFO     : Running command: ['/usr/src/RPM/BUILD/django-graphiql-debug-toolbar-0.2.0/.run_venv/bin/python3', '-m', 'pyproject_installer', 'install', '/usr/src/RPM/BUILD/django-graphiql-debug-toolbar-0.2.0/dist/django_graphiql_debug_toolbar-0.2.0-py3-none-any.whl']
INFO     : Running command: ['/usr/src/RPM/BUILD/django-graphiql-debug-toolbar-0.2.0/.run_venv/bin/python3', '-m', 'pyproject_installer', 'install', '/usr/src/RPM/BUILD/django-graphiql-debug-toolbar-0.2.0/dist/django_graphiql_debug_toolbar-0.2.0-py3-none-any.whl']
INFO     : Running command: ['python3', '-m', 'pytest']
INFO     : Running command: ['python3', '-m', 'pytest']
INFO     : Running command: ['python3', '-m', 'pytest']
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3/site-packages/django/core/files/storage/handler.py", line 26, in __getitem__
  File "/usr/lib/python3/site-packages/django/core/files/storage/handler.py", line 26, in __getitem__
  File "/usr/lib/python3/site-packages/django/core/files/storage/handler.py", line 26, in __getitem__
    return self._storages[alias]
    return self._storages[alias]
    return self._storages[alias]
           ~~~~~~~~~~~~~~^^^^^^^
           ~~~~~~~~~~~~~~^^^^^^^
           ~~~~~~~~~~~~~~^^^^^^^
KeyError: 'staticfiles'
KeyError: 'staticfiles'
KeyError: 'staticfiles'



During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:



Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<frozen runpy>", line 88, in _run_code
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/site-packages/pytest/__main__.py", line 9, in <module>
  File "/usr/lib/python3/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(pytest.console_main())
    raise SystemExit(pytest.console_main())
                     ^^^^^^^^^^^^^^^^^^^^^
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/_pytest/config/__init__.py", line 201, in console_main
  File "/usr/lib/python3/site-packages/_pytest/config/__init__.py", line 201, in console_main
    code = main()
    code = main()
           ^^^^^^
           ^^^^^^
  File "/usr/lib/python3/site-packages/_pytest/config/__init__.py", line 156, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/pluggy/_hooks.py", line 513, in __call__
  File "/usr/lib/python3/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/pluggy/_manager.py", line 120, in _hookexec
  File "/usr/lib/python3/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 139, in _multicall
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 122, in _multicall
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
  File "/usr/lib/python3/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
    config = yield
             ^^^^^
             ^^^^^
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 103, in _multicall
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
  File "/usr/lib/python3/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3/site-packages/_pytest/config/__init__.py", line 1494, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3/site-packages/_pytest/config/__init__.py", line 1398, in _preparse
    self.hook.pytest_load_initial_conftests(
    self.hook.pytest_load_initial_conftests(
  File "/usr/lib/python3/site-packages/pluggy/_hooks.py", line 513, in __call__
  File "/usr/lib/python3/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/pluggy/_manager.py", line 120, in _hookexec
  File "/usr/lib/python3/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 139, in _multicall
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 139, in _multicall
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
    raise exception.with_traceback(exception.__traceback__)
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 122, in _multicall
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 122, in _multicall
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    teardown.throw(exception)  # type: ignore[union-attr]
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
    ^^^^^^^^^^^^^^^^^^^^^^^^^
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
  File "/usr/lib/python3/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
  File "/usr/lib/python3/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
    return (yield)
    return (yield)
    return (yield)
            ^^^^^
            ^^^^^
            ^^^^^
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 122, in _multicall
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 122, in _multicall
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    teardown.throw(exception)  # type: ignore[union-attr]
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
    ^^^^^^^^^^^^^^^^^^^^^^^^^
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/_pytest/capture.py", line 172, in pytest_load_initial_conftests
  File "/usr/lib/python3/site-packages/_pytest/capture.py", line 172, in pytest_load_initial_conftests
  File "/usr/lib/python3/site-packages/_pytest/capture.py", line 172, in pytest_load_initial_conftests
    yield
    yield
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 103, in _multicall
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/pytest_django/plugin.py", line 361, in pytest_load_initial_conftests
    _setup_django(early_config)
  File "/usr/lib/python3/site-packages/pytest_django/plugin.py", line 237, in _setup_django
    django.setup()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/django/core/files/storage/handler.py", line 46, in create_storage
  File "/usr/lib/python3/site-packages/django/core/files/storage/handler.py", line 46, in create_storage
    return storage_cls(**options)
    return storage_cls(**options)
           ^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/django/contrib/staticfiles/storage.py", line 29, in __init__
  File "/usr/lib/python3/site-packages/django/contrib/staticfiles/storage.py", line 29, in __init__
    check_settings(base_url)
    check_settings(base_url)
  File "/usr/lib/python3/site-packages/django/contrib/staticfiles/utils.py", line 49, in check_settings
  File "/usr/lib/python3/site-packages/django/contrib/staticfiles/utils.py", line 49, in check_settings
    raise ImproperlyConfigured(
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the required STATIC_URL setting.
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the required STATIC_URL setting.
INFO     : Command's result: FAILURE
INFO     : Command's result: FAILURE
INFO     : Command's result: FAILURE
INFO     : Command's error: Command '['python3', '-m', 'pytest']' returned non-zero exit status 1.
INFO     : Command's error: Command '['python3', '-m', 'pytest']' returned non-zero exit status 1.
INFO     : Command's error: Command '['python3', '-m', 'pytest']' returned non-zero exit status 1.
error: Bad exit status from /usr/src/tmp/rpm-tmp.56769 (%check)
error: Bad exit status from /usr/src/tmp/rpm-tmp.56769 (%check)
error: Bad exit status from /usr/src/tmp/rpm-tmp.56769 (%check)






RPM build errors:
RPM build errors:
RPM build errors:
    Bad exit status from /usr/src/tmp/rpm-tmp.56769 (%check)
    Bad exit status from /usr/src/tmp/rpm-tmp.56769 (%check)
    Bad exit status from /usr/src/tmp/rpm-tmp.56769 (%check)
Command exited with non-zero status 1
Command exited with non-zero status 1
Command exited with non-zero status 1
1.02user 0.48system 0:01.45elapsed 103%CPU (0avgtext+0avgdata 51464maxresident)k
1.02user 0.48system 0:01.45elapsed 103%CPU (0avgtext+0avgdata 51464maxresident)k
1.02user 0.48system 0:01.45elapsed 103%CPU (0avgtext+0avgdata 51464maxresident)k
0inputs+0outputs (0major+102161minor)pagefaults 0swaps
0inputs+0outputs (0major+102161minor)pagefaults 0swaps
0inputs+0outputs (0major+102161minor)pagefaults 0swaps
hsh-rebuild: rebuild of `python3-module-django-graphiql-debug-toolbar-0.2.0-alt3.src.rpm' failed.
hsh-rebuild: rebuild of `python3-module-django-graphiql-debug-toolbar-0.2.0-alt3.src.rpm' failed.
hsh-rebuild: rebuild of `python3-module-django-graphiql-debug-toolbar-0.2.0-alt3.src.rpm' failed.
Command exited with non-zero status 1
Command exited with non-zero status 1
Command exited with non-zero status 1
4.49user 3.26system 0:17.53elapsed 44%CPU (0avgtext+0avgdata 140976maxresident)k
4.49user 3.26system 0:17.53elapsed 44%CPU (0avgtext+0avgdata 140976maxresident)k
880inputs+0outputs (0major+352698minor)pagefaults 0swaps
